
CREATE TABLE IF NOT EXISTS t_checkin (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    doc_no VARCHAR(50),
    elder_name VARCHAR(50),
    elder_idcard VARCHAR(20),
    elder_phone VARCHAR(20),
    gender VARCHAR(10),
    birth_date DATE,
    age INT,
    address VARCHAR(500),
    bed_no VARCHAR(50),
    checkin_date DATE,
    period_start DATE,
    period_end DATE,
    nursing_level VARCHAR(50),
    deposit DECIMAL(10,2),
    nursing_fee DECIMAL(10,2),
    bed_fee DECIMAL(10,2),
    other_fee DECIMAL(10,2),
    insurance_pay DECIMAL(10,2),
    gov_subsidy DECIMAL(10,2),
    step INT DEFAULT 1,
    step_status VARCHAR(20) DEFAULT 'ÉêÇëÖÐ',
    flow_status VARCHAR(20) DEFAULT 'ÉêÇëÖÐ',
    approval_result VARCHAR(20),
    approval_comment VARCHAR(500),
    contract_no VARCHAR(50),
    contract_name VARCHAR(100),
    contract_file VARCHAR(200),
    sign_date DATE,
    third_party_name VARCHAR(50),
    third_party_phone VARCHAR(20),
    family_json TEXT,
    extra_json TEXT,
    applicant VARCHAR(50),
    apply_time DATETIME,
    finish_time DATETIME,
    ethnicity VARCHAR(20),
    political_status VARCHAR(20),
    religion VARCHAR(20),
    marital_status VARCHAR(20),
    education_level VARCHAR(10),
    income_source VARCHAR(20),
    medical_insurance VARCHAR(30),
    hobbies VARCHAR(20),
    medical_insurance_no VARCHAR(19),
    creator VARCHAR(50),
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
